### ISSUE TITLE
compile on macOS

### ISSUE THREAD

**Issue by JetP1L0t** [MakisChristou/vanitybech#3]
tried to compile on macOS Ventura 13.2.1

brew install automake
... skipped ...
make
... skipped ...
./externs.h:14:10: fatal error: 'sys/prctl.h' file not found

**Comment by MakisChristou** [comment]
Hello. Unfortunately I don't have a Mac so I cannot help much here. It seems like you are missing a header file. A quick ChatGPT prompt suggests that you should run 
`brew install linux-headers` but take it with a grain of salt.

**Comment by JetP1L0t** [comment]
tried it, but it forwards to https://github.com/vgribov/mac-linux-headers with a lot of mess, also with rebuilding it for aarch64
ok, seemed it would be more handy to find a usual pc :(

**Comment by JetP1L0t** [comment]
w
